version: "3.8"

services:

  accounts:
    image: justinphan/bank-app-accounts-service:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - bank-app-network
    
  loans:
    image: justinphan/bank-app-loans-service:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - bank-app-network
    
  cards:
    image: justinphan/bank-app-cards-service:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - bank-app-network
    
networks:
  bank-app-network: